name: Build docker image tensorflow-gpu-base 

on:
  push:
    paths:
      - 'tensorflow-gpu-base/Dockerfile'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0
      -
        name: Login to Dockerhub
        uses: docker/login-action@v1.12.0
        with:
          username:  ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set environment variables for image tagging
        run: |
          echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2.9.0
        with:
          context: ./tensorflow-gpu-base
          file: ./tensorflow-gpu-base/Dockerfile
          push: true
          tags: |
            harvardat/tensorflow-gpu-base:${{ env.SHORT_SHA }}
            harvardat/tensorflow-gpu-base:latest
      -
        name: Image digest                  
        run: echo ${{ steps.docker_build.outputs.digest }}